"""empty message

Revision ID: 0690d684c94b
Revises: cd2f1bc097c9
Create Date: 2020-03-11 17:30:47.063149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0690d684c94b'
down_revision = 'cd2f1bc097c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('ingredients', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'ingredients')
    # ### end Alembic commands ###
